### ISSUE TITLE
Not initializing properly

### ISSUE THREAD

**Issue by catabush05** [dmoggles/blueskysocial#1]
<img width="714" alt="Screenshot 2024-11-08 at 4 43 24 PM" src="https://github.com/user-attachments/assets/b5ef784f-d87d-4ec9-b0b0-eaf168790aaf">

I think there might be an issue with the way that the package is initializing. When I use the provided example code in the README file, I get an error saying the functions are unable to be imported. I found two ways around this: 1. I edited the __init__.py file to import all of the related functions (which allowed me to import them directly from the package when loading into Jupyter) and 2. I imported Client from blueskysocial.client instead of blueskysocial directly. These were both easy workarounds to get the functions available. 

However, it seems that there was a further issue with the Client function specifically. I don't know if this has anything to do with my workarounds (it very well may), but when I went to initialize the Client using Client(user_name, password), it said that the function only takes one positional argument (in this case, self). Similarly, I could not get any of the functions in Client to work, despite trying to work around the issue. 

I am admittedly not very well versed in package management, and this may have been my own doing, but just wanted to give you a heads-up. I made sure that I was using 1.2.0 and uninstalled/installed a few times to no avail.

**Comment by dmoggles** [comment]
Thanks for the heads up, I'll take a look tonight.

**Comment by dmoggles** [comment]
both should be fixed.
```
import blueskysocial as bs
client = bs.Client()
``` 
should now work.  

However, the second issue was with incorrect readme.  The constructor doesn't take any parameters.  Instead, user name and password are passed into the authenticate function.  The readme has been fixed and this 
``` 
import blueskysocial as bs.

client = bs.Client()
client.authenticate(user_name, password)

image = Image('path/to/image.jpg', alt_text='This is an image.')
post = bs.Post('Hello, world!, This is my first post.', images=[image])
client.post(post)
```
should work.
